src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    private ?int $max_size = null;

    #[ORM\Column]
    private ?bool $public = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $created_by = null;

    /**
     * @var Collection<int, Registration>
     */
    #[ORM\OneToMany(targetEntity: Registration::class, mappedBy: 'event')]
    private Collection $registrations;

    public function __construct()
    {
        $this->registrations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function getMaxSize(): ?int
    {
        return $this->max_size;
    }

    public function setMaxSize(int $max_size): static
    {
        $this->max_size = $max_size;

        return $this;
    }

    public function isPublic(): ?bool
    {
        return $this->public;
    }

    public function setPublic(bool $public): static
    {
        $this->public = $public;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): static
    {
        $this->created_by = $created_by;

        return $this;
    }

    /**
     * @return Collection<int, Registration>
     */
    public function getRegistrations(): Collection
    {
        return $this->registrations;
    }

    public function addRegistration(Registration $registration): static
    {
        if (!$this->registrations->contains($registration)) {
            $this->registrations->add($registration);
            $registration->setEvent($this);
        }

        return $this;
    }

    public function removeRegistration(Registration $registration): static
    {
        if ($this->registrations->removeElement($registration)) {
            // set the owning side to null (unless already changed)
            if ($registration->getEvent() === $this) {
                $registration->setEvent(null);
            }
        }

        return $this;
    }

    public function getRemainingPlaces(): int
    {
        return $this->max_size - count($this->registrations);
    }
}

src/Form/EventType.php
<?php

namespace App\Form;

use App\Entity\Event;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', null, [
                'label' => 'Titre',
            ])
            ->add('description', null, [
                'label' => 'Description',
            ])
            ->add('date', null, [
                'widget' => 'single_text',
                'label' => 'Date',
            ])
            ->add('max_size', null, [
                'label' => 'Nombre de places',
            ])
            ->add('public', null, [
                'label' => 'Public',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Event::class,
        ]);
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Form\EventType;
use App\Form\EventFilterType;
use App\Repository\EventRepository;
use App\Repository\RegistrationRepository;
use App\Service\RegistrationService;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use App\Entity\User;

#[Route('/event')]
class EventController extends AbstractController
{
    #[Route('/', name: 'app_event_index', methods: ['GET'])]
    public function index(EventRepository $eventRepository): Response
    {
        $user = $this->getUser();
        $events = $eventRepository->findBy(['created_by' => $user]);

        return $this->render('event/index.html.twig', [
            'events' => $events,
        ]);
    }

    #[Route('/new', name: 'app_event_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $event = new Event();
        $event->setCreatedBy($this->getUser()); // Set the authenticated user as the creator of the event

        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($event);
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/new.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_event_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        if ($event->getCreatedBy() !== $this->getUser()) {
            throw $this->createAccessDeniedException('Vous n\'êtes pas autorisé à modifier cet événement.');
        }

        $form = $this->createForm(EventType::class, $event);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('event/edit.html.twig', [
            'event' => $event,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_event_delete', methods: ['POST'])]
    public function delete(Request $request, Event $event, EntityManagerInterface $entityManager): Response
    {
        if ($event->getCreatedBy() !== $this->getUser()) {
            throw $this->createAccessDeniedException('Vous n\'êtes pas autorisé à supprimer cet événement.');
        }

        if ($this->isCsrfTokenValid('delete'.$event->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($event);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_event_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/list', name: 'app_event_list', methods: ['GET'])]
    public function list(EventRepository $eventRepository, PaginatorInterface $paginator, Request $request): Response
    {
        $form = $this->createForm(EventFilterType::class);
        $allValues = $request->query->all();
        if (isset($allValues[$form->getName()])) {
            $form->submit($allValues[$form->getName()]);
        }

        $queryBuilder = $eventRepository->createQueryBuilder('e');

        if ($form->isSubmitted() && $form->isValid()) {
            $filters = $form->getData();

            if ($filters && $filters['title']) {
                $queryBuilder->andWhere('e.title LIKE :title')
                             ->setParameter('title', '%' . $filters['title'] . '%');
            }

            if ($filters && $filters['date_from']) {
                $queryBuilder->andWhere('e.date >= :date_from')
                             ->setParameter('date_from', $filters['date_from']);
            }

            if ($filters && $filters['date_to']) {
                $queryBuilder->andWhere('e.date <= :date_to')
                             ->setParameter('date_to', $filters['date_to']);
            }

            if (isset($filters['is_public']) && $filters['is_public'] !== null) {
                $queryBuilder->andWhere('e.public = :public')
                             ->setParameter('public', $filters['is_public']);
            }
        }

        if (!$this->getUser()) {
            $queryBuilder->andWhere('e.public = :public')
                         ->setParameter('public', true);
        }

        $pagination = $paginator->paginate(
            $queryBuilder->getQuery(),
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('event/list.html.twig', [
            'pagination' => $pagination,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/registration', name: 'app_event_registration', methods: ['GET'])]
    public function registration(EventRepository $eventRepository, RegistrationRepository $registrationRepository): Response
    {
        $user = $this->getUser();
        $events = $eventRepository->findByNotCreatedByUser($user);
        $registrations = $registrationRepository->findBy(['user' => $user]);

        $registeredEventIds = array_map(function($registration) {
            return $registration->getEvent()->getId();
        }, $registrations);

        return $this->render('event/registration.html.twig', [
            'events' => $events,
            'registeredEventIds' => $registeredEventIds,
        ]);
    }

    #[Route('/event/{id}/register', name: 'app_event_register', methods: ['POST'])]
    public function register(Event $event, RegistrationService $registrationService, MailerInterface $mailer): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $success = $registrationService->register($event, $user);
        $subject = 'Inscription réussie !';
        $template = 'emails/inscription_success.html.twig';
        if ($success) {
            $this->addFlash('success', 'Vous êtes inscrit à l\'événement.');
        } else {
            $this->addFlash('error', 'L\'inscription a échoué.');
            $subject = 'Inscription échouée';
            $template = 'emails/inscription_failed.html.twig';
        }
        $email = (new TemplatedEmail())
            ->from('projet-s6-symfony@mailer.com')
            ->to($user->getEmail())
            ->subject($subject)
            ->htmlTemplate($template)
            ->locale('fr')
            ->context([
                'event' => $event,
                'user' => $user,
            ]);
        $mailer->send($email);

        return $this->redirectToRoute('app_event_registration');
    }

    #[Route('/event/{id}/unregister', name: 'app_event_unregister', methods: ['POST'])]
    public function unregister(Event $event, RegistrationService $registrationService, MailerInterface $mailer): Response
    {
        /** @var User $user */
        $user = $this->getUser();
        $success = $registrationService->unregister($event, $user);
        $subject = 'Désinscription réussie';
        $template = 'emails/annulation_success.html.twig';
        if ($success) {
            $this->addFlash('success', 'Vous êtes désinscrit de l\'événement.');
        } else {
            $this->addFlash('error', 'La désinscription a échoué.');
            $subject = 'Désinscription échouée';
            $template = 'emails/annulation_failed.html.twig';
        }
        $email = (new TemplatedEmail())
            ->from('projet-s6-symfony@mailer.com')
            ->to($user->getEmail())
            ->subject($subject)
            ->htmlTemplate($template)
            ->locale('fr')
            ->context([
                'event' => $event,
                'user' => $user,
            ]);
        $mailer->send($email);

        return $this->redirectToRoute('app_event_registration');
    }
}

templates/event/_delete_form.html.twig
<form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Êtes vous sûr de supprimer cet événement ?');" class="block">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
    <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded w-full">
        Supprimer   
    </button>
</form>

templates/event/_form.html.twig
{{ form_start(form, { 'attr': { 'class': 'space-y-6' } }) }}
    <div class="space-y-4">
        {% for field in form %}
            {% if field.vars.name != '_token' %}
                <div class="form-group">
                    {{ form_label(field, null, { 'label_attr': { 'class': 'block text-sm font-medium text-gray-700' } }) }}
                    {{ form_widget(field) }}
                    {{ form_errors(field) }}
                </div>
            {% else %}
                {{ form_widget(field) }}
            {% endif %}
        {% endfor %}
    </div>
    <button class="w-full bg-blue-700 hover:bg-blue-900 text-white font-bold py-2 px-4 rounded">
        {{ button_label|default('Sauvegarder') }}
    </button>
{{ form_end(form) }}

templates/event/edit.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Modifier un événement{% endblock %}

{% block main %}
    <div class="flex items-center justify-center min-h-screen bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
        <div class="max-w-md w-full bg-white p-8 rounded-lg shadow-md">
            <h1 class="text-2xl font-bold mb-6 text-center">Modifier un événement</h1>

            {{ include('event/_form.html.twig', {'button_label': 'Modifier'}) }}

            <div class="my-4 text-center">
                <a href="{{ path('app_event_index') }}" class="text-indigo-600 hover:text-indigo-900">
                    Retour à la liste des événements
                </a>
            </div>

            {{ include('event/_delete_form.html.twig') }}


        </div>
    </div>
{% endblock %}

templates/event/index.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Mes événements{% endblock %}

{% block main %}
    <h1 class="text-2xl font-bold mb-6">Mes événements</h1>

    <div class="overflow-x-auto">
        <table class="min-w-full bg-white border border-gray-200 divide-y divide-gray-200">
            <thead class="bg-gray-50">
                <tr>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Titre</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Description</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nombres de places</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Public</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            {% for event in events %}
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap">{{ event.title }}</td>
                    <td class="px-6 py-4 whitespace-nowrap">{{ event.description }}</td>
                    <td class="px-6 py-4 whitespace-nowrap">{{ event.date ? event.date|date('Y-m-d H:i:s') : '' }}</td>
                    <td class="px-6 py-4 whitespace-nowrap">{{ event.maxSize }}</td>
                    <td class="px-6 py-4 whitespace-nowrap">{{ event.public ? 'Oui' : 'Non' }}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium flex gap-4">
                        {% if event.createdBy == app.user %}
                        <a href="{{ path('app_event_edit', {'id': event.id}) }}" class="text-indigo-600 hover:text-indigo-900"><i class="fas fa-pen"></i></a>
                        <form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Êtes vous sûr de supprimer cet événement ?');">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
                            <button type="submit">
                                <i class="fas fa-trash text-red-500 hover:text-red-700"></i>
                            </button>
                        </form>
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6" class="px-6 py-4 whitespace-nowrap text-center text-gray-500">Vous n'avez pas encore créé d'événement</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <div class="mt-4">
        <a href="{{ path('app_event_new') }}" class="inline-block bg-blue-700 hover:bg-blue-900 text-white font-bold py-2 px-4 rounded">
            Créer un nouvel événement
        </a>
    </div>
{% endblock %}

templates/event/list.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Liste des événements{% endblock %}

{% block main %}
    <h1 class="text-2xl font-bold mb-6">Liste des événements</h1>

    {{ form_start(form, { 'method': 'GET', 'attr': { 'class': 'space-y-4' } }) }}
        <div class="flex gap-4">
            {{ form_row(form.title) }}
            {{ form_row(form.date_from) }}
            {{ form_row(form.date_to) }}
            {{ form_row(form.is_public) }}
        </div>
        <button type="submit" class="bg-blue-700 hover:bg-blue-900 text-white font-bold py-2 px-4 rounded mt-4">
            Filtrer
        </button>
    {{ form_end(form) }}

    <div class="overflow-x-auto mt-6">
        <table class="min-w-full bg-white border border-gray-200 divide-y divide-gray-200">
            <thead class="bg-gray-50">
                <tr>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Titre</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Description</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nombres de places</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Public</th>
                    <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                </tr>
            </thead>
            <tbody class="bg-white divide-y divide-gray-200">
            {% for event in pagination %}
                <tr>
                    <td class="px-6 py-4 whitespace-nowrap">{{ event.title }}</td>
                    <td class="px-6 py-4 whitespace-nowrap">{{ event.description }}</td>
                    <td class="px-6 py-4 whitespace-nowrap">{{ event.date|date('Y-m-d H:i:s') }}</td>
                    <td class="px-6 py-4 whitespace-nowrap">{{ event.maxSize }}</td>
                    <td class="px-6 py-4 whitespace-nowrap">{{ event.public ? 'Oui' : 'Non' }}</td>
                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium flex gap-4">
                        {% if event.createdBy == app.user %}
                        <a href="{{ path('app_event_edit', {'id': event.id}) }}" class="text-indigo-600 hover:text-indigo-900"><i class="fas fa-pen"></i></a>
                        <form method="post" action="{{ path('app_event_delete', {'id': event.id}) }}" onsubmit="return confirm('Êtes vous sûr de supprimer cet événement ?');">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ event.id) }}">
                            <button type="submit">
                                <i class="fas fa-trash text-red-500 hover:text-red-700"></i>
                            </button>
                        </form>
                        {% endif %}
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6" class="px-6 py-4 whitespace-nowrap text-center text-gray-500">Aucun événement trouvé</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="mt-4">
        {{ knp_pagination_render(pagination) }}
    </div>

    <div class="mt-4">
        <a href="{{ path('app_event_new') }}" class="inline-block bg-blue-700 hover:bg-blue-900 text-white font-bold py-2 px-4 rounded">
            Créer un nouvel événement
        </a>
    </div>
{% endblock %}

templates/event/new.html.twig
{% extends 'layout.html.twig' %}

{% block title %}Nouvel événement{% endblock %}

{% block main %}
    <div class="flex items-center justify-center min-h-screen bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
        <div class="max-w-md w-full bg-white p-8 rounded-lg shadow-md">
            <h1 class="text-2xl font-bold mb-6 text-center">Créer un nouvel événement</h1>

            {{ include('event/_form.html.twig') }}

            <div class="mt-4 text-center">
                <a href="{{ path('app_event_index') }}" class="text-indigo-600 hover:text-indigo-900">
                    Retour à la liste des événements
                </a>
            </div>
        </div>
    </div>
{% endblock %}

templates/event/registration.html.twig
{% extends 'layout.html.twig' %}

{% block title %}S'inscrire à des événements{% endblock %}

{% block main %}
    <h1 class="text-2xl font-bold mb-6">S'inscrire à des événements</h1>

    {% if events is empty %}
        <p>Aucun événement disponible pour l'instant.</p>
    {% else %}
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {% for event in events %}
                <div class="bg-white border border-gray-200 p-4 rounded">
                    <h2 class="text-xl font-bold">{{ event.title }}</h2>
                    <p>{{ event.description }}</p>
                    <p>Date: {{ event.date|date('Y-m-d H:i') }}</p>
                    <p>Places restantes: {{ event.getRemainingPlaces() }}</p>

                    {% if event.id in registeredEventIds %}
                        <form method="post" action="{{ path('app_event_unregister', {id: event.id}) }}">
                            <button type="submit" class="bg-red-700 hover:bg-red-900 text-white font-bold py-2 px-4 rounded mt-4">
                                Se désinscrire
                            </button>
                        </form>
                    {% else %}
                        {% if event.getRemainingPlaces() > 0 %}
                            <form method="post" action="{{ path('app_event_register', {id: event.id}) }}">
                                <button type="submit" class="bg-blue-700 hover:bg-blue-900 text-white font-bold py-2 px-4 rounded mt-4">
                                    S'inscrire
                                </button>
                            </form>
                        {% else %}
                            <p class="text-red-500">Complet</p>
                        {% endif %}
                    {% endif %}
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endblock %}